# 表示老师对于课程在每个时段的课程满意度的集合
teacher_satisfaction: 
    # 时段1
    - 0.1
    # 时段2
    - 0.2
    # 时段3
    - 0.26
    # 时段4
    - 0.3
    # 时段5
    - 0.14

# 表示学生对于课程在每个时段的课程满意度的集合
student_satisfaction:
    # 时段1
    - 0.14
    # 时段2
    - 0.26
    # 时段3
    - 0.2
    # 时段4
    - 0.3
    # 时段5
    - 0.1

# 自定义星期的名称
name_of_days:
    - 星期一
    - 星期二
    - 星期三
    - 星期四
    - 星期五

# 五个时段的信息
sections:
    - 8:00-9:40
    - 10:10-11:50
    - 14:20-16:00
    - 16:30-18:10
    - 19:00-21:35

# 教师评价的比重
teacher_weight: 0.5

# 学生评价的比重
student_weight: 0.5

# 班级名称
classes_name:
    - 23级智科一班
    - 23级智科二班
    - 23级智能交通一班
    - 23级智能交通二班
    - 22级智科一班
    - 22级智科二班
    - 22级交通一班
    - 22级交通二班
    - 21级智科一班
    - 21级智科二班
    - 21级交通一班
    - 21级交通二班
    - 20级智科一班
    - 20级智科二班
    - 20级交通一班
    - 20级交通二班
